# Unordered list style
MD004:
  style: dash

# Unordered list style
MD013:
  tables: false
  code_blocks: false

# Ordered list item prefix
MD029:
  style: one

# Spaces after list markers
MD030:
  ul_single: 1
  ol_single: 1
  ul_multi: 1
  ol_multi: 1

# no-inline-html
MD033:
  allowed_elements:
    - p
    - img
    - h2
    - div

# Code block style
MD046:
  style: fenced
